version: '3.8'

services:
  auth:
    image: mess_auth_service:0.1.0
    restart: always
    container_name: mess_auth
    hostname: mess_auth
    depends_on:
      - auth_db
    env_file:
      - auth_prod.env
    ports:
      - "8000:80"

  auth_db:
    container_name: auth_db
    image: postgres:16
    restart: always
    volumes:
      - auth_db:/var/lib/postgresql/data
    env_file:
      - auth_prod_db.env
  
#  user:
#    image: mess-user-service
#    restart: always
#    container_name: mess_user
#    hostname: mess-user
#    depends_on:
#      - user_db
#
#  user_db:
#    container_name: user_db
#    image: postgres:16
#    restart: always
#    environment:
#      POSTGRES_DB: mess_user
#    volumes:
#      - user_db:/var/lib/postgresql/data
#
#  message:
#    image: mess-message-service
#    restart: always
#    container_name: mess_message
#    hostname: mess-message
#    depends_on:
#      - message_db
#
#  message_db:
#    container_name: message_db
#    image: postgres:16
#    restart: always
#    environment:
#      POSTGRES_DB: mess_message
#    volumes:
#      - message_db:/var/lib/postgresql/data
#
#  nginx:
#    build:
#      context: .
#      dockerfile: Dockerfile.nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - app

volumes:
  auth_db:
